name = "bensoltan-ecommerce"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[env.production]
name = "bensoltan-ecommerce-prod"
routes = [
  { pattern = "bensoltandecommerce.tn", zone_name = "bensoltandecommerce.tn" },
  { pattern = "www.bensoltandecommerce.tn", zone_name = "bensoltandecommerce.tn" }
]

[env.preview]
name = "bensoltan-ecommerce-preview"